### ISSUE TITLE
Unable to install Semaphore with curl + sh

### ISSUE THREAD

**Issue by jeroenrinzema** [jexia/semaphore#126]
Hi, 

I am trying to run Semaphore on Ubuntu and executing below command. 

```
$ curl -k https://raw.githubusercontent.com/jexia/semaphore/master/install.sh | sh -s -- -b ./bin v2.0.0-beta.19
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9626  100  9626    0     0   4022      0  0:00:02  0:00:02 --:--:--  4020
jexia/semaphore info checking GitHub for tag 'v2.0.0-beta.19'
jexia/semaphore crit unable to find 'v2.0.0-beta.19' - use 'latest' or see https://github.com/jexia/semaphore/releases for details
```

But getting above mentioned error. Is there anything wrong in command. Could you please help me?

_Originally posted by @Purushottamlpa in https://github.com/jexia/semaphore/issues/94#issuecomment-695212620_

**Comment by jeroenrinzema** [comment]
👋 @Purushottamlpa, thanks for the report. Would you be able to run the command again with debugging enabled?

```sh
$ curl https://raw.githubusercontent.com/jexia/semaphore/master/install.sh | sh -s -- -d -b ./bin v2.0.0-beta.19
```

**Comment by Purushottamlpa** [comment]
@jeroenrinzema, thanks for your response. Tried with above command. Please find response:

curl -k https://raw.githubusercontent.com/jexia/semaphore/master/install.sh | sh -s -- -d -b  ./bin v2.0.0-beta.19
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9626  100  9626    0     0   6210      0  0:00:01  0:00:01 --:--:--  6210
jexia/semaphore info checking GitHub for tag 'v2.0.0-beta.19'
jexia/semaphore debug http_download https://github.com/jexia/semaphore/releases/v2.0.0-beta.19
jexia/semaphore debug http_download_curl received HTTP status 000
jexia/semaphore crit unable to find 'v2.0.0-beta.19' - use 'latest' or see https://github.com/jexia/semaphore/releases for details

**Comment by jeroenrinzema** [comment]
@Purushottamlpa, the received HTTP status code is `000` which often means that a network error occurred. Would you be able to check if you are able to resolve the DNS for github.com and githubusercontent.com?

```
$ dig github.com
$ dig githubusercontent.com
```

In the meantime would you be able to download the binaries manually from the [latest release](https://github.com/jexia/semaphore/releases). Please select a `linux` binary for your CPU architecture.

**Comment by Purushottamlpa** [comment]
@jeroenrinzema, thanks again. I made semaphore up with binaries.
