### ISSUE TITLE
Implement pretty errors in all existing CLI commands

### ISSUE THREAD

**Issue by jeroenrinzema** [jexia/semaphore#143]
Errors thrown inside Semaphore could be unwrapped (#137) to construct error messages in multiple formats (ex: text, JSON, and CSV). The pretty err implementation unwraps the error and returns a human-readable format.

This implementation has to be implemented in the available commands (validate, generate, etc.) to ensure that a human-understandable error is returned when thrown. It is probably best to move this implementation into a generic package for ease of use.

https://github.com/jexia/semaphore/blob/bc52565f0a8286e467f1da1a4952fa818e86e7ff/cmd/semaphore/daemon/daemon.go#L35-L47

For new contributors please check out #138 for more information on how to contribute to the Semaphore project.

**Comment by chinvib66** [comment]
@jeroenrinzema Can I take up this issue?

**Comment by jeroenrinzema** [comment]
@chinvib66 sounds good 😃

**Comment by chinvib66** [comment]
Thanks for the approval! 

I have a small query...
The above PrettyError function returns instances of error even if it fails to prettify. So, I replaced `return errors.New("\n" + msg)` with `return errors.New("\nPrettyError Message: \n" + msg)` for using the new msg prefix to verify whether error is prettified or not, while running tests.

Is this approach acceptable or do you have any recommended approach?

**Comment by jeroenrinzema** [comment]
👋 @chinvib66, thanks for your question.

If an error occurs while constructing the error message is the returned error wrapped with [additional information](https://github.com/jexia/semaphore/blob/bc52565f0a8286e467f1da1a4952fa818e86e7ff/pkg/prettyerr/text_formatter.go#L31). At the moment is the only possibility for `template.New` to throw an error by passing an invalid template. Optionally would it be possible to fall back to a known working template (ex: [`DefaultTextFormat`](https://github.com/jexia/semaphore/blob/bc52565f0a8286e467f1da1a4952fa818e86e7ff/pkg/prettyerr/text_formatter.go#L10)) You could include this inside your changes if you want.

It would probably be a good idea to make a small adjustment to the [`TextFormatter`](https://github.com/jexia/semaphore/blob/bc52565f0a8286e467f1da1a4952fa818e86e7ff/pkg/prettyerr/text_formatter.go#L16-L44) method. Instead of returning an error if the execution of a [template fails](https://github.com/jexia/semaphore/blob/bc52565f0a8286e467f1da1a4952fa818e86e7ff/pkg/prettyerr/text_formatter.go#L39). Is it possible to wrap the returned (template) error and fallback on the defined [`error.Message`](https://github.com/jexia/semaphore/blob/bc52565f0a8286e467f1da1a4952fa818e86e7ff/pkg/prettyerr/error.go#L18) instead.

Since we already append additional information to a constructed error message if the construction of an error message fails would it not be necessary to add a prefix to a successfully generated error message.
