### ISSUE TITLE
refactor TestTextFormatter to use t.Run

### ISSUE THREAD

**Issue by jeroenrinzema** [jexia/semaphore#145]
`TestTextFormatter` has to be refactored to make use of `t.Run` to allow to execute isolated test cases.

https://github.com/jexia/semaphore/blob/08f11a20fde1090085670ad2a98fcf5268941f1d/pkg/prettyerr/text_formatter_test.go#L6-L67

**Comment by HemantJoshi11** [comment]
@jeroenrinzema is it open to pick ?

**Comment by jeroenrinzema** [comment]
@HemantJoshi11 go ahead!

**Comment by chinvib66** [comment]
@jeroenrinzema I have just completed refactoring the test file. Shall I submit a PR, or let @HemantJoshi11  handle it?

**Comment by jeroenrinzema** [comment]
@HemantJoshi11 did you start working on the PR already? If not do you mind if @chinvib66 resolves this issue?

**Comment by HemantJoshi11** [comment]
Ok. Go head.

**Comment by jeroenrinzema** [comment]
@HemantJoshi11 I have just created a new small refactor issue (#147). You could pick up this issue instead if you want.
