### ISSUE TITLE
Refactor template.Parse to return specs.Template

### ISSUE THREAD

**Issue by jeroenrinzema** [jexia/semaphore#147]
The `template.Parse` method at the moment returns a `specs.Property`. This method has to be refactored to return a `specs.Template` instead after #119. The `TODO` for this issue could be found inside the [HCL provider](https://github.com/jexia/semaphore/blob/master/pkg/providers/hcl/specs.go#L718).

https://github.com/jexia/semaphore/blob/08f11a20fde1090085670ad2a98fcf5268941f1d/pkg/specs/template/template.go#L152-L168

**Comment by veger** [comment]
Fixed by #191
