### ISSUE TITLE
OpenAPI3 generator crash when no input is defined in flow

### ISSUE THREAD

**Issue by reidlai** [jexia/semaphore#177]
**Describe the bug**
OpenAPI3 generator crash when no input is defined in flow.  After checking master branch, the code still can't handle when input is nil ( pkg/generators/openapi3/generator.go line 150)

**To Reproduce**
Please include as much as possible information to reproduce the issue:
- create config.hcl and flow.hcl
- define the flow without input
- Run "semaphore generate openapi3"
- exception about nil pointer at pkg/generators/openapi3/generator.go line 150

**Expected behaviour**
Should ouptut openapi3 format in stdout

**Additional context**

**Comment by veger** [comment]
Thank you for your bug report!
Sorry for the later response, but we were focused on some other things...

I believe it got fixed by the PR I opened
